// apps/web/app/(dashboard)/dashboard/leads/page.tsx
import { auth } from "@/auth";
import BookingStatusSelect from "./booking-status-select";

interface Booking {
  id: string;
  listing_id: string;
  user_id: string;
  preferred_date: string | null;
  preferred_time: string | null;
  status: "pending" | "confirmed" | "cancelled" | "completed";
  notes: string | null;
  created_at: string;
}

interface LoanInquiry {
  id: string;
  listing_id: string;
  loan_amount: number | null;
  tenure_months: number | null;
  employment_type: string | null;
  annual_income: number | null;
  status: string;
  created_at: string;
}

async function getReceivedBookings(token: string): Promise<Booking[]> {
  const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";
  try {
    const res = await fetch(`${apiUrl}/bookings/received`, {
      headers: { Authorization: `Bearer ${token}` },
      cache: "no-store",
    });
    if (!res.ok) return [];
    return res.json();
  } catch {
    return [];
  }
}

async function getReceivedLoanInquiries(token: string): Promise<LoanInquiry[]> {
  const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";
  try {
    const res = await fetch(`${apiUrl}/loans/inquiries/received`, {
      headers: { Authorization: `Bearer ${token}` },
      cache: "no-store",
    });
    if (!res.ok) return [];
    return res.json();
  } catch {
    return [];
  }
}

function formatINR(n: number) {
  if (n >= 10_00_000) return `₹${(n / 10_00_000).toFixed(2)}L`;
  return `₹${(n / 1_000).toFixed(0)}K`;
}

const BOOKING_STATUS_COLORS: Record<string, string> = {
  pending:   "bg-accent/15 text-accent-foreground border border-accent/30",
  confirmed: "bg-chart-2/15 text-chart-2",
  completed: "bg-success/15 text-success",
  cancelled: "bg-destructive/15 text-destructive",
};

const LOAN_STATUS_COLORS: Record<string, string> = {
  submitted:  "bg-accent/15 text-accent-foreground border border-accent/30",
  processing: "bg-chart-2/15 text-chart-2",
  approved:   "bg-success/15 text-success",
  rejected:   "bg-destructive/15 text-destructive",
};

export default async function LeadsPage() {
  const session = await auth();
  const token = (session as { accessToken?: string })?.accessToken ?? "";
  const [bookings, loanInquiries] = await Promise.all([
    getReceivedBookings(token),
    getReceivedLoanInquiries(token),
  ]);

  return (
    <div className="max-w-4xl space-y-10">
      <div>
        <h1 className="text-3xl font-display font-semibold mb-1">Leads</h1>
        <p className="text-muted-foreground text-sm">
          Test drive requests and loan inquiries on your listings.
        </p>
      </div>

      {/* Test Drive Bookings */}
      <section>
        <h2 className="text-base font-semibold mb-4">Test Drive Requests</h2>
        {bookings.length === 0 ? (
          <div className="rounded-xl border p-10 text-center text-muted-foreground text-sm">
            No test drive requests yet.
          </div>
        ) : (
          <div className="rounded-xl border overflow-hidden">
            <table className="w-full text-sm">
              <thead className="border-b bg-muted/30">
                <tr>
                  <th className="text-left px-4 py-3 font-medium">Date</th>
                  <th className="text-left px-4 py-3 font-medium">Preferred Date</th>
                  <th className="text-left px-4 py-3 font-medium">Notes</th>
                  <th className="text-left px-4 py-3 font-medium">Status</th>
                  <th className="text-left px-4 py-3 font-medium">Update</th>
                </tr>
              </thead>
              <tbody className="divide-y">
                {bookings.map((booking) => (
                  <tr key={booking.id} className="hover:bg-muted/20 transition-colors">
                    <td className="px-4 py-3 text-muted-foreground">
                      {new Date(booking.created_at).toLocaleDateString("en-IN")}
                    </td>
                    <td className="px-4 py-3">
                      {booking.preferred_date
                        ? new Date(booking.preferred_date).toLocaleDateString("en-IN")
                        : "—"}
                      {booking.preferred_time && ` ${booking.preferred_time}`}
                    </td>
                    <td className="px-4 py-3 text-muted-foreground max-w-xs truncate">
                      {booking.notes ?? "—"}
                    </td>
                    <td className="px-4 py-3">
                      <span className={`px-2 py-0.5 rounded-full text-xs font-medium capitalize ${BOOKING_STATUS_COLORS[booking.status] ?? ""}`}>
                        {booking.status}
                      </span>
                    </td>
                    <td className="px-4 py-3">
                      <BookingStatusSelect bookingId={booking.id} current={booking.status} token={token} />
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </section>

      {/* Loan Inquiries */}
      <section>
        <h2 className="text-base font-semibold mb-4">Loan Inquiries</h2>
        {loanInquiries.length === 0 ? (
          <div className="rounded-xl border p-10 text-center text-muted-foreground text-sm">
            No loan inquiries yet.
          </div>
        ) : (
          <div className="rounded-xl border overflow-hidden">
            <table className="w-full text-sm">
              <thead className="border-b bg-muted/30">
                <tr>
                  <th className="text-left px-4 py-3 font-medium">Date</th>
                  <th className="text-left px-4 py-3 font-medium">Loan Amount</th>
                  <th className="text-left px-4 py-3 font-medium">Tenure</th>
                  <th className="text-left px-4 py-3 font-medium">Employment</th>
                  <th className="text-left px-4 py-3 font-medium">Income</th>
                  <th className="text-left px-4 py-3 font-medium">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y">
                {loanInquiries.map((inquiry) => (
                  <tr key={inquiry.id} className="hover:bg-muted/20 transition-colors">
                    <td className="px-4 py-3 text-muted-foreground">
                      {new Date(inquiry.created_at).toLocaleDateString("en-IN")}
                    </td>
                    <td className="px-4 py-3 font-medium">
                      {inquiry.loan_amount ? formatINR(inquiry.loan_amount) : "—"}
                    </td>
                    <td className="px-4 py-3">
                      {inquiry.tenure_months ? `${inquiry.tenure_months} mo` : "—"}
                    </td>
                    <td className="px-4 py-3 capitalize text-muted-foreground">
                      {inquiry.employment_type?.replace("_", " ") ?? "—"}
                    </td>
                    <td className="px-4 py-3">
                      {inquiry.annual_income ? formatINR(inquiry.annual_income) + " p.a." : "—"}
                    </td>
                    <td className="px-4 py-3">
                      <span className={`px-2 py-0.5 rounded-full text-xs font-medium capitalize ${LOAN_STATUS_COLORS[inquiry.status] ?? ""}`}>
                        {inquiry.status}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </section>
    </div>
  );
}

// apps/gaadiiq-angular/src/app/pages/leads/leads.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { environment } from '../../../environments/environment';
import { AuthService } from '../../services/auth.service';

type BookingStatus = 'pending' | 'confirmed' | 'cancelled' | 'completed';

interface Booking {
  id: string;
  listing_id: string;
  user_id: string;
  preferred_date: string | null;
  preferred_time: string | null;
  status: BookingStatus;
  notes: string | null;
  created_at: string;
}

interface LoanInquiry {
  id: string;
  listing_id: string;
  loan_amount: number | null;
  tenure_months: number | null;
  employment_type: string | null;
  annual_income: number | null;
  status: string;
  created_at: string;
}

@Component({
  selector: 'app-leads',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './leads.component.html',
  styleUrl: './leads.component.scss',
})
export class LeadsComponent implements OnInit {
  private readonly http = inject(HttpClient);
  private readonly router = inject(Router);
  private readonly auth = inject(AuthService);

  readonly bookingStatuses: BookingStatus[] = ['pending', 'confirmed', 'completed', 'cancelled'];

  bookings = signal<Booking[]>([]);
  loanInquiries = signal<LoanInquiry[]>([]);
  loading = signal(true);

  ngOnInit(): void {
    if (!this.auth.isLoggedIn()) {
      void this.router.navigate(['/login']);
      return;
    }

    // Both lists are independent; a failure in one leaves the other usable
    // rather than blanking the page.
    this.http.get<Booking[]>(`${environment.apiUrl}/bookings/received`).subscribe({
      next: (rows) => this.bookings.set(rows ?? []),
      error: () => this.bookings.set([]),
      complete: () => this.loading.set(false),
    });

    this.http.get<LoanInquiry[]>(`${environment.apiUrl}/loans/inquiries/received`).subscribe({
      next: (rows) => this.loanInquiries.set(rows ?? []),
      error: () => this.loanInquiries.set([]),
    });
  }

  updateStatus(booking: Booking, next: BookingStatus): void {
    if (next === booking.status) return;
    const previous = booking.status;

    this.bookings.update((rows) =>
      rows.map((b) => (b.id === booking.id ? { ...b, status: next } : b)),
    );

    this.http
      .patch(`${environment.apiUrl}/bookings/${booking.id}/status`, { status: next })
      .subscribe({
        // Roll back on failure so the dropdown never shows a status the server
        // did not accept.
        error: () =>
          this.bookings.update((rows) =>
            rows.map((b) => (b.id === booking.id ? { ...b, status: previous } : b)),
          ),
      });
  }

  formatINR(n: number | null): string {
    if (n === null || n === undefined) return '—';
    if (n >= 10_00_000) return `₹${(n / 10_00_000).toFixed(2)}L`;
    return `₹${(n / 1_000).toFixed(0)}K`;
  }

  employment(value: string | null): string {
    return value ? value.replace(/_/g, ' ') : '—';
  }
}

<div class="leads-page">
  <div class="container">
    <header class="leads-head">
      <h1>Leads</h1>
      <p>Test drive requests and loan inquiries on your listings.</p>
    </header>

    @if (loading()) {
      <p class="state">Loading…</p>
    } @else {
      <section class="leads-section">
        <h2>Test Drive Requests</h2>

        @if (bookings().length === 0) {
          <div class="empty">No test drive requests yet.</div>
        } @else {
          <div class="table-wrap">
            <table>
              <thead>
                <tr>
                  <th>Received</th>
                  <th>Preferred Date</th>
                  <th>Notes</th>
                  <th>Status</th>
                  <th>Update</th>
                </tr>
              </thead>
              <tbody>
                @for (b of bookings(); track b.id) {
                  <tr>
                    <td class="muted">{{ b.created_at | date: 'd MMM y' }}</td>
                    <td>
                      {{ b.preferred_date ? (b.preferred_date | date: 'd MMM y') : '—' }}
                      @if (b.preferred_time) { <span class="muted">{{ b.preferred_time }}</span> }
                    </td>
                    <td class="muted truncate">{{ b.notes ?? '—' }}</td>
                    <td>
                      <span class="pill" [class]="'status-' + b.status">{{ b.status }}</span>
                    </td>
                    <td>
                      <select [ngModel]="b.status" (ngModelChange)="updateStatus(b, $event)">
                        @for (s of bookingStatuses; track s) {
                          <option [value]="s">{{ s }}</option>
                        }
                      </select>
                    </td>
                  </tr>
                }
              </tbody>
            </table>
          </div>
        }
      </section>

      <section class="leads-section">
        <h2>Loan Inquiries</h2>

        @if (loanInquiries().length === 0) {
          <div class="empty">No loan inquiries yet.</div>
        } @else {
          <div class="table-wrap">
            <table>
              <thead>
                <tr>
                  <th>Received</th>
                  <th>Loan Amount</th>
                  <th>Tenure</th>
                  <th>Employment</th>
                  <th>Income</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                @for (q of loanInquiries(); track q.id) {
                  <tr>
                    <td class="muted">{{ q.created_at | date: 'd MMM y' }}</td>
                    <td class="strong">{{ formatINR(q.loan_amount) }}</td>
                    <td>{{ q.tenure_months ? q.tenure_months + ' mo' : '—' }}</td>
                    <td class="muted capitalize">{{ employment(q.employment_type) }}</td>
                    <td>{{ q.annual_income ? formatINR(q.annual_income) + ' p.a.' : '—' }}</td>
                    <td>
                      <span class="pill" [class]="'status-' + q.status">{{ q.status }}</span>
                    </td>
                  </tr>
                }
              </tbody>
            </table>
          </div>
        }
      </section>
    }
  </div>
</div>
