// apps/gaadiiq-angular/src/app/pages/tco/tco.component.ts
import { Component, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

type FuelType = 'petrol' | 'diesel' | 'electric' | 'cng';

interface FuelDefaults {
  price: number;
  mileage: number;
  label: string;
  /** Wording changes for electric: ₹/kWh and km/kWh rather than ₹/L and km/L. */
  priceLabel: string;
  mileageLabel: string;
}

const FUEL_DEFAULTS: Record<FuelType, FuelDefaults> = {
  petrol: { price: 100, mileage: 15, label: 'Petrol', priceLabel: 'Fuel Price (₹/L)', mileageLabel: 'Mileage (km/L)' },
  diesel: { price: 88, mileage: 18, label: 'Diesel', priceLabel: 'Fuel Price (₹/L)', mileageLabel: 'Mileage (km/L)' },
  electric: { price: 8, mileage: 100, label: 'Electric', priceLabel: 'Electricity (₹/kWh)', mileageLabel: 'Range (km/kWh)' },
  cng: { price: 75, mileage: 22, label: 'CNG', priceLabel: 'CNG Price (₹/kg)', mileageLabel: 'Mileage (km/kg)' },
};

/**
 * Annual depreciation rates, an approximation of the Indian used-car market.
 * Year 6 onwards reuses the final rate.
 */
const DEPRECIATION = [0.2, 0.15, 0.12, 0.10, 0.08];

@Component({
  selector: 'app-tco',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './tco.component.html',
  styleUrl: './tco.component.scss',
})
export class TcoComponent {
  readonly fuelTypes = Object.keys(FUEL_DEFAULTS) as FuelType[];
  readonly fuelDefaults = FUEL_DEFAULTS;

  purchasePrice = signal(1000000);
  fuelType = signal<FuelType>('petrol');
  kmPerYear = signal(15000);
  yearsOwned = signal(5);
  insurancePremiumPct = signal(3);
  maintenancePerYear = signal(15000);
  fuelPricePerLitre = signal(100);
  mileageKmpl = signal(15);

  /** Labels track the selected fuel so electric reads in kWh, not litres. */
  priceLabel = computed(() => FUEL_DEFAULTS[this.fuelType()].priceLabel);
  mileageLabel = computed(() => FUEL_DEFAULTS[this.fuelType()].mileageLabel);

  private years = computed(() => Math.min(Math.max(1, this.yearsOwned()), 10));

  resaleValue = computed(() => {
    let value = this.purchasePrice();
    for (let y = 0; y < this.years(); y++) {
      value *= 1 - DEPRECIATION[Math.min(y, DEPRECIATION.length - 1)];
    }
    return value;
  });

  depreciation = computed(() => this.purchasePrice() - this.resaleValue());
  private totalKm = computed(() => this.kmPerYear() * this.years());

  fuelCost = computed(() => {
    const mileage = this.mileageKmpl();
    // Guard the divisor: the input is user-editable and 0 would yield Infinity.
    return mileage > 0 ? (this.totalKm() / mileage) * this.fuelPricePerLitre() : 0;
  });

  insurance = computed(() => this.purchasePrice() * (this.insurancePremiumPct() / 100) * this.years());
  maintenance = computed(() => this.maintenancePerYear() * this.years());

  total = computed(() => this.depreciation() + this.fuelCost() + this.insurance() + this.maintenance());
  perYear = computed(() => this.total() / this.years());
  perKm = computed(() => (this.totalKm() > 0 ? this.total() / this.totalKm() : 0));

  retainedPct = computed(() => {
    const price = this.purchasePrice();
    return price > 0 ? (this.resaleValue() / price) * 100 : 0;
  });

  selectFuel(ft: FuelType): void {
    this.fuelType.set(ft);
    this.fuelPricePerLitre.set(FUEL_DEFAULTS[ft].price);
    this.mileageKmpl.set(FUEL_DEFAULTS[ft].mileage);
  }

  /** Share of the grand total, for the breakdown bars. */
  share(value: number): number {
    const total = this.total();
    return total > 0 ? (value / total) * 100 : 0;
  }

  formatINR(n: number): string {
    if (!isFinite(n)) return '—';
    if (n >= 1_00_00_000) return `₹${(n / 1_00_00_000).toFixed(2)} Cr`;
    if (n >= 1_00_000) return `₹${(n / 1_00_000).toFixed(1)} L`;
    return `₹${Math.round(n).toLocaleString('en-IN')}`;
  }
}

<div class="tco-page">
  <header class="tco-hero">
    <div class="container">
      <span class="eyebrow">Cost Analysis</span>
      <h1>Total Cost of <span class="gradient-text">Ownership</span></h1>
      <p>Beyond the sticker price — understand the true multi-year cost of owning any car.</p>
    </div>
  </header>

  <div class="container">
    <div class="tco-grid">
      <!-- Inputs -->
      <section class="controls-card">
        <h2>Vehicle Details</h2>

        <label class="field">
          <span class="field-label">Purchase Price</span>
          <div class="field-row">
            <span class="affix">₹</span>
            <input type="number" min="100000" step="50000"
                   [ngModel]="purchasePrice()" (ngModelChange)="purchasePrice.set(+$event)" />
          </div>
        </label>

        <div class="field">
          <span class="field-label">Fuel Type</span>
          <div class="chip-row">
            @for (ft of fuelTypes; track ft) {
              <button type="button" class="chip" [class.active]="fuelType() === ft"
                      (click)="selectFuel(ft)">
                {{ fuelDefaults[ft].label }}
              </button>
            }
          </div>
        </div>

        <div class="field-pair">
          <label class="field">
            <span class="field-label">KM per Year</span>
            <div class="field-row">
              <input type="number" min="1000" step="1000"
                     [ngModel]="kmPerYear()" (ngModelChange)="kmPerYear.set(+$event)" />
            </div>
          </label>
          <label class="field">
            <span class="field-label">Years Owned</span>
            <div class="field-row">
              <input type="number" min="1" max="10" step="1"
                     [ngModel]="yearsOwned()" (ngModelChange)="yearsOwned.set(+$event)" />
            </div>
          </label>
        </div>

        <h2 class="section-break">Running Costs</h2>

        <div class="field-pair">
          <label class="field">
            <span class="field-label">{{ priceLabel() }}</span>
            <div class="field-row">
              <input type="number" min="1" step="1"
                     [ngModel]="fuelPricePerLitre()" (ngModelChange)="fuelPricePerLitre.set(+$event)" />
            </div>
          </label>
          <label class="field">
            <span class="field-label">{{ mileageLabel() }}</span>
            <div class="field-row">
              <input type="number" min="1" step="1"
                     [ngModel]="mileageKmpl()" (ngModelChange)="mileageKmpl.set(+$event)" />
            </div>
          </label>
        </div>

        <label class="field">
          <span class="field-label">Insurance (% of value / year)</span>
          <div class="field-row">
            <input type="number" min="0" step="0.5"
                   [ngModel]="insurancePremiumPct()" (ngModelChange)="insurancePremiumPct.set(+$event)" />
            <span class="affix">%</span>
          </div>
        </label>

        <label class="field">
          <span class="field-label">Maintenance per Year</span>
          <div class="field-row">
            <span class="affix">₹</span>
            <input type="number" min="0" step="5000"
                   [ngModel]="maintenancePerYear()" (ngModelChange)="maintenancePerYear.set(+$event)" />
          </div>
        </label>
      </section>

      <!-- Results -->
      <section class="results">
        <div class="summary-row">
          <div class="summary-card primary">
            <p class="summary-label">Total {{ yearsOwned() }}yr Cost</p>
            <p class="summary-value">{{ formatINR(total()) }}</p>
          </div>
          <div class="summary-card">
            <p class="summary-label">Per Year</p>
            <p class="summary-value">{{ formatINR(perYear()) }}</p>
          </div>
          <div class="summary-card">
            <p class="summary-label">Per KM</p>
            <p class="summary-value">₹{{ perKm() | number: '1.1-1' }}</p>
          </div>
        </div>

        <div class="resale-card">
          <div>
            <p class="summary-label">Estimated resale value after {{ yearsOwned() }} years</p>
            <p class="resale-value">{{ formatINR(resaleValue()) }}</p>
          </div>
          <span class="badge">{{ retainedPct() | number: '1.0-0' }}% retained</span>
        </div>

        <div class="breakdown-card">
          <h2>Cost Breakdown</h2>

          @for (row of [
            { label: 'Depreciation', value: depreciation(), cls: 'bar-depreciation' },
            { label: 'Fuel / Energy', value: fuelCost(), cls: 'bar-fuel' },
            { label: 'Insurance', value: insurance(), cls: 'bar-insurance' },
            { label: 'Maintenance', value: maintenance(), cls: 'bar-maintenance' }
          ]; track row.label) {
            <div class="bar-row">
              <div class="bar-head">
                <span class="bar-label">{{ row.label }}</span>
                <span class="bar-figures">
                  <strong>{{ formatINR(row.value) }}</strong>
                  <span class="bar-pct">({{ share(row.value) | number: '1.0-0' }}%)</span>
                </span>
              </div>
              <div class="bar-track">
                <div class="bar-fill" [class]="row.cls" [style.width.%]="share(row.value)"></div>
              </div>
            </div>
          }

          <div class="grand-total">
            <span>Grand Total</span>
            <strong>{{ formatINR(total()) }}</strong>
          </div>
        </div>

        <p class="disclaimer">
          * Depreciation uses market-standard rates (20% → 15% → 12% → 10% → 8% per year).
          Actual costs vary by city, driving style, and insurer.
        </p>
      </section>
    </div>
  </div>
</div>

// apps/web/app/tco/page.tsx
"use client";

import { useState, useMemo } from "react";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Calculator, TrendingDown, Fuel, Shield, Wrench, IndianRupee } from "lucide-react";
import ToolPageHeader from "@/components/tool-page-header";

interface TCOInputs {
  purchasePrice: number;
  fuelType: "petrol" | "diesel" | "electric" | "cng";
  kmPerYear: number;
  yearsOwned: number;
  insurancePremiumPct: number;
  maintenancePerYear: number;
  fuelPricePerLitre: number;
  mileageKmpl: number;
}

interface TCOResult {
  depreciation: number;
  fuelCost: number;
  insurance: number;
  maintenance: number;
  total: number;
  perYear: number;
  perKm: number;
  resaleValue: number;
}

const DEFAULTS: TCOInputs = {
  purchasePrice: 1000000,
  fuelType: "petrol",
  kmPerYear: 15000,
  yearsOwned: 5,
  insurancePremiumPct: 3,
  maintenancePerYear: 15000,
  fuelPricePerLitre: 100,
  mileageKmpl: 15,
};

const FUEL_DEFAULTS: Record<TCOInputs["fuelType"], { price: number; mileage: number; label: string }> = {
  petrol: { price: 100, mileage: 15, label: "Petrol" },
  diesel: { price: 88, mileage: 18, label: "Diesel" },
  electric: { price: 8, mileage: 100, label: "Electric (₹/kWh, km/kWh equiv)" },
  cng: { price: 75, mileage: 22, label: "CNG" },
};

// Annual depreciation rates (India used car market approximation)
const DEPRECIATION = [0.2, 0.15, 0.12, 0.10, 0.08];

function calcTCO(inputs: TCOInputs): TCOResult {
  const { purchasePrice, kmPerYear, yearsOwned, insurancePremiumPct, maintenancePerYear, fuelPricePerLitre, mileageKmpl } = inputs;
  const years = Math.min(Math.max(1, yearsOwned), 10);

  // Depreciation — compound over years
  let resaleValue = purchasePrice;
  for (let y = 0; y < years; y++) {
    const rate = DEPRECIATION[Math.min(y, DEPRECIATION.length - 1)];
    resaleValue *= (1 - rate);
  }
  const depreciation = purchasePrice - resaleValue;

  const totalKm = kmPerYear * years;
  const fuelCost = (totalKm / mileageKmpl) * fuelPricePerLitre;
  const insurance = purchasePrice * (insurancePremiumPct / 100) * years;
  const maintenance = maintenancePerYear * years;

  const total = depreciation + fuelCost + insurance + maintenance;
  const perYear = total / years;
  const perKm = total / totalKm;

  return { depreciation, fuelCost, insurance, maintenance, total, perYear, perKm, resaleValue };
}

function formatINR(n: number, decimals = 0) {
  if (n >= 1_00_00_000) return `₹${(n / 1_00_00_000).toFixed(2)} Cr`;
  if (n >= 1_00_000) return `₹${(n / 1_00_000).toFixed(1)} L`;
  return `₹${n.toLocaleString("en-IN", { maximumFractionDigits: decimals })}`;
}

function NumberInput({
  label,
  value,
  onChange,
  prefix,
  suffix,
  step = 1000,
  min = 0,
}: {
  label: string;
  value: number;
  onChange: (v: number) => void;
  prefix?: string;
  suffix?: string;
  step?: number;
  min?: number;
}) {
  return (
    <div>
      <label className="text-sm font-medium text-foreground mb-1.5 block">{label}</label>
      <div className="flex items-center gap-2">
        {prefix && <span className="text-muted-foreground text-sm shrink-0">{prefix}</span>}
        <Input
          type="number"
          value={value}
          min={min}
          step={step}
          onChange={(e) => onChange(Number(e.target.value))}
          className="w-full"
        />
        {suffix && <span className="text-muted-foreground text-sm shrink-0">{suffix}</span>}
      </div>
    </div>
  );
}

function CostBar({ label, value, total, color, icon }: { label: string; value: number; total: number; color: string; icon: React.ReactNode }) {
  const pct = total > 0 ? (value / total) * 100 : 0;
  return (
    <div>
      <div className="flex items-center justify-between text-sm mb-1">
        <div className="flex items-center gap-2 text-muted-foreground">
          {icon}
          {label}
        </div>
        <div className="flex items-center gap-2">
          <span className="font-medium">{formatINR(value)}</span>
          <span className="text-xs text-muted-foreground">({pct.toFixed(0)}%)</span>
        </div>
      </div>
      <div className="h-2 bg-muted rounded-full overflow-hidden">
        <div className={`h-full rounded-full ${color} transition-all duration-700`} style={{ width: `${pct}%` }} />
      </div>
    </div>
  );
}

export default function TCOPage() {
  const [inputs, setInputs] = useState<TCOInputs>(DEFAULTS);

  const set = (key: keyof TCOInputs, value: number | string) => {
    setInputs((prev) => ({ ...prev, [key]: value }));
  };

  const setFuelType = (ft: TCOInputs["fuelType"]) => {
    const d = FUEL_DEFAULTS[ft];
    setInputs((prev) => ({ ...prev, fuelType: ft, fuelPricePerLitre: d.price, mileageKmpl: d.mileage }));
  };

  const result = useMemo(() => calcTCO(inputs), [inputs]);

  return (
    <main className="min-h-screen bg-background">
      <ToolPageHeader
        eyebrow="Cost Analysis"
        title="Total Cost of Ownership"
        subtitle="Beyond the sticker price — understand the true multi-year cost of owning any car."
        icon={<Calculator className="h-6 w-6 text-accent" />}
      />
      <div className="max-w-5xl mx-auto px-4 py-10">

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Inputs */}
          <div className="bg-card rounded-2xl border p-6 flex flex-col gap-5">
            <h2 className="font-semibold text-lg">Vehicle Details</h2>

            <NumberInput
              label="Purchase Price"
              value={inputs.purchasePrice}
              onChange={(v) => set("purchasePrice", v)}
              prefix="₹"
              step={50000}
              min={100000}
            />

            <div>
              <label className="text-sm font-medium mb-1.5 block">Fuel Type</label>
              <div className="flex flex-wrap gap-2">
                {(Object.keys(FUEL_DEFAULTS) as TCOInputs["fuelType"][]).map((ft) => (
                  <button
                    key={ft}
                    onClick={() => setFuelType(ft)}
                    className={`px-3 py-1.5 rounded-lg text-sm border transition-all
                      ${inputs.fuelType === ft
                        ? "border-accent bg-accent/10 text-accent font-medium"
                        : "border-border hover:border-accent/40"}`}
                  >
                    {FUEL_DEFAULTS[ft].label.split(" ")[0]}
                  </button>
                ))}
              </div>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <NumberInput
                label="KM per Year"
                value={inputs.kmPerYear}
                onChange={(v) => set("kmPerYear", v)}
                step={1000}
                min={1000}
              />
              <NumberInput
                label="Years Owned"
                value={inputs.yearsOwned}
                onChange={(v) => set("yearsOwned", Math.min(10, Math.max(1, v)))}
                step={1}
                min={1}
              />
            </div>

            <h2 className="font-semibold text-lg pt-2 border-t">Running Costs</h2>

            <div className="grid grid-cols-2 gap-4">
              <NumberInput
                label={inputs.fuelType === "electric" ? "Electricity (₹/kWh)" : "Fuel Price (₹/L)"}
                value={inputs.fuelPricePerLitre}
                onChange={(v) => set("fuelPricePerLitre", v)}
                step={1}
                min={1}
              />
              <NumberInput
                label={inputs.fuelType === "electric" ? "Range (km/kWh)" : "Mileage (km/L)"}
                value={inputs.mileageKmpl}
                onChange={(v) => set("mileageKmpl", v)}
                step={1}
                min={1}
              />
            </div>

            <NumberInput
              label="Insurance (% of value/year)"
              value={inputs.insurancePremiumPct}
              onChange={(v) => set("insurancePremiumPct", v)}
              suffix="%"
              step={0.5}
              min={0}
            />
            <NumberInput
              label="Maintenance per Year"
              value={inputs.maintenancePerYear}
              onChange={(v) => set("maintenancePerYear", v)}
              prefix="₹"
              step={5000}
              min={0}
            />
          </div>

          {/* Results */}
          <div className="flex flex-col gap-5">
            {/* Summary cards */}
            <div className="grid grid-cols-3 gap-3">
              <div className="bg-primary/10 rounded-xl p-4 text-center">
                <p className="text-xs text-muted-foreground mb-1">Total {inputs.yearsOwned}yr Cost</p>
                <p className="text-xl font-bold text-primary">{formatINR(result.total)}</p>
              </div>
              <div className="bg-card rounded-xl border p-4 text-center">
                <p className="text-xs text-muted-foreground mb-1">Per Year</p>
                <p className="text-xl font-bold">{formatINR(result.perYear)}</p>
              </div>
              <div className="bg-card rounded-xl border p-4 text-center">
                <p className="text-xs text-muted-foreground mb-1">Per KM</p>
                <p className="text-xl font-bold">₹{result.perKm.toFixed(1)}</p>
              </div>
            </div>

            {/* Resale value */}
            <div className="bg-card rounded-xl border p-5 flex items-center gap-4">
              <TrendingDown className="h-8 w-8 text-accent shrink-0" />
              <div>
                <p className="text-sm text-muted-foreground">Estimated Resale Value after {inputs.yearsOwned} years</p>
                <p className="text-2xl font-bold">{formatINR(result.resaleValue)}</p>
              </div>
              <Badge variant="outline" className="ml-auto shrink-0">
                {((result.resaleValue / inputs.purchasePrice) * 100).toFixed(0)}% retained
              </Badge>
            </div>

            {/* Cost breakdown bars */}
            <div className="bg-card rounded-2xl border p-6 flex flex-col gap-5">
              <h2 className="font-semibold text-lg">Cost Breakdown</h2>
              <CostBar
                label="Depreciation"
                value={result.depreciation}
                total={result.total}
                color="bg-chart-5"
                icon={<TrendingDown className="h-4 w-4" />}
              />
              <CostBar
                label="Fuel / Energy"
                value={result.fuelCost}
                total={result.total}
                color="bg-chart-1"
                icon={<Fuel className="h-4 w-4" />}
              />
              <CostBar
                label="Insurance"
                value={result.insurance}
                total={result.total}
                color="bg-chart-2"
                icon={<Shield className="h-4 w-4" />}
              />
              <CostBar
                label="Maintenance"
                value={result.maintenance}
                total={result.total}
                color="bg-chart-4"
                icon={<Wrench className="h-4 w-4" />}
              />

              <div className="pt-4 border-t flex items-center justify-between">
                <span className="font-medium flex items-center gap-1.5">
                  <IndianRupee className="h-4 w-4" />
                  Grand Total
                </span>
                <span className="text-xl font-bold text-primary">{formatINR(result.total)}</span>
              </div>
            </div>

            <p className="text-xs text-muted-foreground px-1">
              * Depreciation uses market-standard rates (20%→15%→12%→10%→8% per year).
              Actual costs vary by city, driving style, and insurer.
            </p>
          </div>
        </div>
      </div>
    </main>
  );
}
