// apps/web/app/notifications/page.tsx
"use client";

import { useCallback, useEffect, useState } from "react";
import { useSession } from "next-auth/react";
import { useRouter } from "next/navigation";

interface Notification {
  id: string;
  type: string;
  title: string;
  body: string | null;
  listing_id: string | null;
  is_read: boolean;
  created_at: string;
}

const TYPE_ICONS: Record<string, string> = {
  booking_received: "🚗",
  booking_confirmed: "✅",
  booking_cancelled: "❌",
  loan_inquiry_received: "💰",
  price_drop: "📉",
  listing_viewed: "👁",
  system: "🔔",
};

export default function NotificationsPage() {
  const { data: session, status } = useSession();
  const router = useRouter();
  const token = (session as { accessToken?: string })?.accessToken;

  const [notifications, setNotifications] = useState<Notification[]>([]);
  const [loading, setLoading] = useState(true);

  const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";

  useEffect(() => {
    if (status === "unauthenticated") router.push("/login");
  }, [status, router]);

  const fetchNotifications = useCallback(async () => {
    if (!token) return;
    setLoading(true);
    try {
      const r = await fetch(`${apiUrl}/notifications?limit=50`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      if (r.ok) setNotifications(await r.json());
    } finally {
      setLoading(false);
    }
  }, [token, apiUrl]);

  /* eslint-disable react-hooks/set-state-in-effect */
  useEffect(() => {
    void fetchNotifications();
  }, [fetchNotifications]);
  /* eslint-enable react-hooks/set-state-in-effect */

  async function markRead(id: string) {
    if (!token) return;
    await fetch(`${apiUrl}/notifications/${id}/read`, {
      method: "PATCH",
      headers: { Authorization: `Bearer ${token}` },
    });
    setNotifications((prev) =>
      prev.map((n) => (n.id === id ? { ...n, is_read: true } : n))
    );
  }

  async function markAllRead() {
    if (!token) return;
    await fetch(`${apiUrl}/notifications/mark-all-read`, {
      method: "POST",
      headers: { Authorization: `Bearer ${token}` },
    });
    setNotifications((prev) => prev.map((n) => ({ ...n, is_read: true })));
  }

  const unread = notifications.filter((n) => !n.is_read).length;

  return (
    <main className="max-w-2xl mx-auto px-4 py-8">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold">Notifications</h1>
          {unread > 0 && (
            <p className="text-sm text-muted-foreground mt-0.5">{unread} unread</p>
          )}
        </div>
        {unread > 0 && (
          <button
            onClick={markAllRead}
            className="text-sm text-primary hover:underline"
          >
            Mark all read
          </button>
        )}
      </div>

      {loading ? (
        <div className="text-center py-20 text-muted-foreground text-sm">Loading…</div>
      ) : notifications.length === 0 ? (
        <div className="rounded-xl border p-16 text-center">
          <p className="text-4xl mb-3">🔔</p>
          <p className="font-medium">No notifications yet</p>
          <p className="text-sm text-muted-foreground mt-1">
            You&apos;ll get alerts for bookings, inquiries, and price drops here.
          </p>
        </div>
      ) : (
        <div className="rounded-xl border divide-y overflow-hidden">
          {notifications.map((n) => (
            <div
              key={n.id}
              onClick={() => !n.is_read && markRead(n.id)}
              className={`flex gap-4 px-5 py-4 cursor-pointer hover:bg-muted/40 transition-colors ${
                !n.is_read ? "bg-primary/5" : ""
              }`}
            >
              <span className="text-xl shrink-0 mt-0.5">{TYPE_ICONS[n.type] ?? "🔔"}</span>
              <div className="flex-1 min-w-0">
                <p className={`text-sm leading-snug ${!n.is_read ? "font-semibold" : ""}`}>
                  {n.title}
                </p>
                {n.body && (
                  <p className="text-sm text-muted-foreground mt-0.5">{n.body}</p>
                )}
                <p className="text-xs text-muted-foreground mt-1">
                  {new Date(n.created_at).toLocaleDateString("en-IN", {
                    weekday: "short", day: "numeric", month: "short",
                    hour: "2-digit", minute: "2-digit",
                  })}
                </p>
              </div>
              {!n.is_read && (
                <span className="w-2.5 h-2.5 rounded-full bg-primary shrink-0 mt-1.5" />
              )}
            </div>
          ))}
        </div>
      )}
    </main>
  );
}

// apps/gaadiiq-angular/src/app/pages/notifications/notifications.component.ts
import { Component, computed, inject, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { Router } from '@angular/router';
import { environment } from '../../../environments/environment';
import { AuthService } from '../../services/auth.service';

interface Notification {
  id: string;
  type: string;
  title: string;
  body: string | null;
  listing_id: string | null;
  is_read: boolean;
  created_at: string;
}

const TYPE_ICONS: Record<string, string> = {
  booking_received: '🚗',
  booking_confirmed: '✅',
  booking_cancelled: '❌',
  loan_inquiry_received: '💰',
  price_drop: '📉',
  listing_viewed: '👁',
  system: '🔔',
};

@Component({
  selector: 'app-notifications',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './notifications.component.html',
  styleUrl: './notifications.component.scss',
})
export class NotificationsComponent implements OnInit {
  private readonly http = inject(HttpClient);
  private readonly router = inject(Router);
  private readonly auth = inject(AuthService);

  notifications = signal<Notification[]>([]);
  loading = signal(true);

  unread = computed(() => this.notifications().filter((n) => !n.is_read).length);

  ngOnInit(): void {
    if (!this.auth.isLoggedIn()) {
      void this.router.navigate(['/login']);
      return;
    }
    this.load();
  }

  /** authInterceptor attaches the Supabase bearer token to apiUrl requests. */
  private load(): void {
    this.loading.set(true);
    this.http
      .get<Notification[]>(`${environment.apiUrl}/notifications`, { params: { limit: 50 } })
      .subscribe({
        next: (rows) => {
          this.notifications.set(rows ?? []);
          this.loading.set(false);
        },
        error: () => this.loading.set(false),
      });
  }

  icon(type: string): string {
    return TYPE_ICONS[type] ?? '🔔';
  }

  markRead(n: Notification): void {
    if (n.is_read) return;
    // Update locally first so the row responds immediately; a failed PATCH only
    // means the badge reappears on the next load, which is the harmless
    // direction to be wrong in.
    this.notifications.update((rows) =>
      rows.map((r) => (r.id === n.id ? { ...r, is_read: true } : r)),
    );
    this.http.patch(`${environment.apiUrl}/notifications/${n.id}/read`, {}).subscribe({
      error: () => this.load(),
    });
  }

  markAllRead(): void {
    if (this.unread() === 0) return;
    this.notifications.update((rows) => rows.map((r) => ({ ...r, is_read: true })));
    this.http.post(`${environment.apiUrl}/notifications/mark-all-read`, {}).subscribe({
      error: () => this.load(),
    });
  }
}

<div class="notif-page">
  <div class="container">
    <header class="notif-head">
      <div>
        <h1>Notifications</h1>
        @if (unread() > 0) {
          <p class="unread-count">{{ unread() }} unread</p>
        }
      </div>
      @if (unread() > 0) {
        <button type="button" class="link-btn" (click)="markAllRead()">Mark all read</button>
      }
    </header>

    @if (loading()) {
      <p class="state">Loading…</p>
    } @else if (notifications().length === 0) {
      <div class="empty">
        <p class="empty-icon">🔔</p>
        <p class="empty-title">No notifications yet</p>
        <p class="empty-body">
          You&rsquo;ll get alerts for bookings, inquiries, and price drops here.
        </p>
      </div>
    } @else {
      <ul class="notif-list">
        @for (n of notifications(); track n.id) {
          <li class="notif-row" [class.unread]="!n.is_read" (click)="markRead(n)">
            <span class="notif-icon">{{ icon(n.type) }}</span>
            <div class="notif-body">
              <p class="notif-title" [class.bold]="!n.is_read">{{ n.title }}</p>
              @if (n.body) {
                <p class="notif-text">{{ n.body }}</p>
              }
              <p class="notif-date">
                {{ n.created_at | date: 'EEE, d MMM, h:mm a' }}
              </p>
            </div>
            @if (!n.is_read) {
              <span class="dot" aria-label="unread"></span>
            }
          </li>
        }
      </ul>
    }
  </div>
</div>
